### ISSUE TITLE
ParseError from specific utterances

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/fallback-duckduckgo#11]
**Describe the bug**
Certain utterances result in ParseError

**To Reproduce**
1. "Hey Mycroft, what is four score and seven years ago"
2. See error:
```
2021-04-28 01:45:30.463 | ERROR | 804 | mycroft.skills.mycroft_skill.mycroft_skill:on_error:835 | An error occurred while processing a request in Duckduckgo Skill
Traceback (most recent call last):
File “/home/pi/mycroft-core/mycroft/skills/mycroft_skill/event_container.py”, line 66, in wrapper
handler(message)
File “/home/pi/mycroft-core/mycroft/skills/common_query_skill.py”, line 76, in __handle_question_query
result = self.CQS_match_query_phrase(search_phrase)
File “/opt/mycroft/skills/mycroft-fallback-duck-duck-go.mycroftai/init.py”, line 133, in CQS_match_query_phrase
answer = self.respond(query[len(test):])
File “/opt/mycroft/skills/mycroft-fallback-duck-duck-go.mycroftai/init.py”, line 109, in respond
r = ddg.query(query)
File “/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/ddg3.py”, line 29, in query
xml = ElementTree.fromstring(response)
File “/usr/lib/python3.7/xml/etree/ElementTree.py”, line 1315, in XML
parser.feed(text)
File “”, line None
```

**Environment (please complete the following information):**
 - Device type: Mark II
 - Mycroft-core version: 20.8.1
 - Mycroft container: 2021-04-08

Thanks to Wallyllama for reporting this.

**Comment by damndemento** [comment]
same here on PI 3b+
`18:10:45.824 | INFO     |  6203 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-fallback-duck-duck-go.mycroftai
 18:10:45.918 | INFO     |  6203 | mycroft.skills.settings:get_local_settings:83 | /home/pi/.config/mycroft/skills/mycroft-fallback-duck-duck-go.mycroftai/settings.json
 18:10:45.927 | ERROR    |  6203 | mycroft.skills.skill_loader:_create_skill_instance:295 | Skill __init__ failed with TypeError('expected str, bytes or os.PathLike object, not NoneType')
Traceback (most recent call last):
  File "/home/pi/mycroft-core/mycroft/skills/skill_loader.py", line 292, in _create_skill_instance
    self.instance = skill_module.create_skill()
  File "/opt/mycroft/skills/mycroft-fallback-duck-duck-go.mycroftai/__init__.py", line 294, in create_skill
    return DuckduckgoSkill()
  File "/opt/mycroft/skills/mycroft-fallback-duck-duck-go.mycroftai/__init__.py", line 54, in __init__
    super(DuckduckgoSkill, self).__init__()
  File "/home/pi/mycroft-core/mycroft/skills/common_query_skill.py", line 71, in __init__
    with open(noise_words_filename) as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType
 18:10:45.935 | ERROR    |  6203 | mycroft.skills.skill_loader:_communicate_load_status:351 | Skill mycroft-fallback-duck-duck-go.mycroftai failed to load
`
