### ISSUE TITLE
loading of skill fails on Pi3b+ fresh install

### ISSUE THREAD

**Issue by damndemento** [MycroftAI/fallback-duckduckgo#19]
error remains after restarting pi or reloading skills
```
18:10:45.824 | INFO     |  6203 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-fallback-duck-duck-go.mycroftai
 18:10:45.918 | INFO     |  6203 | mycroft.skills.settings:get_local_settings:83 | /home/pi/.config/mycroft/skills/mycroft-fallback-duck-duck-go.mycroftai/settings.json
 18:10:45.927 | ERROR    |  6203 | mycroft.skills.skill_loader:_create_skill_instance:295 | Skill __init__ failed with TypeError('expected str, bytes or os.PathLike object, not NoneType')
Traceback (most recent call last):
  File "/home/pi/mycroft-core/mycroft/skills/skill_loader.py", line 292, in _create_skill_instance
    self.instance = skill_module.create_skill()
  File "/opt/mycroft/skills/mycroft-fallback-duck-duck-go.mycroftai/__init__.py", line 294, in create_skill
    return DuckduckgoSkill()
  File "/opt/mycroft/skills/mycroft-fallback-duck-duck-go.mycroftai/__init__.py", line 54, in __init__
    super(DuckduckgoSkill, self).__init__()
  File "/home/pi/mycroft-core/mycroft/skills/common_query_skill.py", line 71, in __init__
    with open(noise_words_filename) as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType
 18:10:45.935 | ERROR    |  6203 | mycroft.skills.skill_loader:_communicate_load_status:351 | Skill mycroft-fallback-duck-duck-go.mycroftai failed to load
```

**Comment by krisgesling** [comment]
Hey there, the bug here was actually in mycroft-core but I believe it's been fixed. Can you make sure you're running the latest version of mycroft-core?

```
cd /home/pi/mycroft-core
git pull
```

and if it's still a problem can you post the output of `git status`?

**Comment by damndemento** [comment]
Everything up to date...
```
(.venv) pi@PICROFT1:~/mycroft-core $ git pull
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 6 (delta 4), reused 6 (delta 4), pack-reused 0
Unpacking objects: 100% (6/6), done.
From https://github.com/MycroftAI/mycroft-core
   35fd704e19..3155954291  mark-ii/qa -> origin/mark-ii/qa
Already up to date.
(.venv) pi@PICROFT1:~/mycroft-core $ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   mycroft/configuration/mycroft.conf

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        audio_setup.sh
        custom_setup.sh
        mycroft/client/speech/recognizer/model/de-de/
        mycroft/client/speech/recognizer/model/de/

no changes added to commit (use "git add" and/or "git commit -a")

```
thanks for having a look at it

**Comment by damndemento** [comment]
language is set to "de-de"
meanwhile I installed german dict for pocketsphinx - so it isn't a fresh install anymore ;)

**Comment by krisgesling** [comment]
Yeah, the fix hasn't been pushed to stable yet. But if you switch to the dev branch of mycroft-core it will stop failing.
```
cd ~/mycroft-core
git checkout dev
./dev_setup.sh
```

**Comment by damndemento** [comment]
ok thanx a ton! ;)
