### ISSUE TITLE
New issue comming on new version of mycroft 18.2.5

### ISSUE THREAD

**Issue by HellCatVN** [MycroftAI/fallback-duckduckgo#3]
![screenshot_20180514_093017](https://user-images.githubusercontent.com/17523567/39975887-4d7b0216-575b-11e8-977e-0ecb834060b3.png)
09:27:44.897 - mycroft.skills.core:load_skill:144 - ERROR - Failed to load skill: mycroft-fallback-duck-duck-go.mycroftai
Traceback (most recent call last):
File "/home/hellcatvn/mycroft-core/mycroft/skills/core.py", line 115, in load_skill
('.py', 'rb', imp.PY_SOURCE)
File "/usr/lib/python3.6/imp.py", line 235, in load_module
return load_source(name, filename, file)
File "/usr/lib/python3.6/imp.py", line 172, in load_source
module = _load(spec)
File "<frozen importlib._bootstrap>", line 684, in _load
File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 678, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/opt/mycroft/skills/mycroft-fallback-duck-duck-go.mycroftai/__init__.py", line 16, in <module>
import duckduckgo as ddg
ModuleNotFoundError: No module named 'duckduckgo'

**Comment by TREE-Ind** [comment]
I've just updated my Git install of Mycroft to the latest dev version, and have experienced the same issue.  Though it doesn't look like an issue with the Mycroft code, with the switch to Python3 it looks like the pip install of duckduckgo2 may be broken in some way.  I had to use the forked version linked below to get the skill to load and run correctly, downloaded and installed manually within the "new" Mycroft virtualenv being used for Python3+.

https://github.com/taciturasa/duckduckgo-python3

Flagging for Mycroft Team: @forslund

**Comment by forslund** [comment]
I think the change is already added (#2), it's just the skills repo that needs updating. I'll push the change during the day.
